#!/bin/sh

if [ $# -ne 2 ]; then echo "USAGE:  use_negative_branch  slave  master"; exit; fi

RUNDIR=$PWD
SLAVE=$1
MASTER=$2
TRACE=`printf 'S%04d.AA.BXY.semd' $SLAVE`
ADJCC='adj_cc.f90'


#prepare directories
rm -rf   DATA SEM OUTPUT_FILES OUTPUT_ALL
mkdir -p DATA SEM OUTPUT_FILES OUTPUT_ALL DATA/NOISE_TOMOGRAPHY OUTPUT_FILES/NOISE_TOMOGRAPHY


#prepare files
cp SOURCE_noise           DATA/SOURCE
cp STATIONS_noise  DATA/STATIONS
cp uniform.dat            DATA/
echo $MASTER >            DATA/NOISE_TOMOGRAPHY/irec_master
if [ -f S_squared ]; then cp S_squared DATA/NOISE_TOMOGRAPHY/; fi
if [ -f model_velocity.dat_input ]; then cp model_velocity.dat_input DATA/; fi


#compile
rm xmshefem2D
rm xspecfem2D
cd ../..
make
cd $RUNDIR
ln -s ../../bin/xmeshfem2D .
ln -s ../../bin/xspecfem2D .


#simulation 1
cp Par_file_noise_1  DATA/Par_file
./xmeshfem2D; ./xspecfem2D
mkdir OUTPUT_ALL/step_1
#mv OUTPUT_FILES/image*       OUTPUT_ALL/step_1
mv *histogram*               OUTPUT_ALL/step_1
mv OUTPUT_FILES/*.semd       OUTPUT_ALL/step_1
mv DATA/Par_file             OUTPUT_ALL/step_1
mv OUTPUT_FILES/mask*        OUTPUT_ALL/
mv OUTPUT_FILES/mesh_????    OUTPUT_ALL/
mv OUTPUT_FILES/model*       OUTPUT_ALL/


#simulation 2
cp Par_file_noise_2  DATA/Par_file
./xmeshfem2D; ./xspecfem2D
mkdir OUTPUT_ALL/step_2
#mv OUTPUT_FILES/image*       OUTPUT_ALL/step_2
mv *histogram*               OUTPUT_ALL/step_2
cp OUTPUT_FILES/*.semd       OUTPUT_ALL/step_2
mv DATA/Par_file             OUTPUT_ALL/step_2


#write zero traces
awk '{printf(" %12.6f %12.6f\n",$1,0.)}' < OUTPUT_FILES/$TRACE > SEM/zero
cd SEM/
for ((ii=1; ii<=3; ++ii))
do
  cp zero `printf S%04d.AA.BXX.adj $ii`
  cp zero `printf S%04d.AA.BXY.adj $ii`
  cp zero `printf S%04d.AA.BXZ.adj $ii`
done
cd ..


#write master trace
sed -i'.bak' 's/use_positive_branch = .[a-z]*./use_positive_branch = .false./' $ADJCC
sed -i'.bak' 's/use_negative_branch = .[a-z]*./use_negative_branch = .true./' $ADJCC
sed -i'.bak' 's/use_custom_window = .[a-z]*./use_custom_window = .false./' $ADJCC
sed -i'.bak' 's/time_reverse = .[a-z]*./time_reverse = .false./' $ADJCC

gfortran $ADJCC -o adj_run
cp OUTPUT_FILES/$TRACE SEM/
./adj_run SEM/$TRACE
rename '.semd' '' SEM/$TRACE.adj


#simulation 3
cp Par_file_noise_3  DATA/Par_file
./xmeshfem2D; ./xspecfem2D
mkdir OUTPUT_ALL/step_3
#mv OUTPUT_FILES/image*       OUTPUT_ALL/step_3
mv *histogram*               OUTPUT_ALL/step_3
mv SEM/*Y.adj                OUTPUT_ALL/step_3
mv DATA/Par_file             OUTPUT_ALL/step_3
mv OUTPUT_FILES/proc*        OUTPUT_ALL/
mv OUTPUT_FILES/snapshot*    OUTPUT_ALL/

