        INTEGER SCOTCH_ARCHDIM
        INTEGER SCOTCH_GEOMDIM
        INTEGER SCOTCH_GRAPHDIM
        INTEGER SCOTCH_MAPDIM
        INTEGER SCOTCH_MESHDIM
        INTEGER SCOTCH_ORDERDIM
        INTEGER SCOTCH_STRATDIM
        PARAMETER (SCOTCH_ARCHDIM  = 4)
        PARAMETER (SCOTCH_GEOMDIM  = 2)
        PARAMETER (SCOTCH_GRAPHDIM = 12)
        PARAMETER (SCOTCH_MAPDIM   = 10)
        PARAMETER (SCOTCH_MESHDIM  = 15)
        PARAMETER (SCOTCH_ORDERDIM = 11)
        PARAMETER (SCOTCH_STRATDIM = 1)
