#!/bin/bash
#
# noise tomography simulation 3
#
NREC=$1
IREC=$2
ISRC=$IREC

rm log.*
rm DATA/Par_file
rm OUTPUT_FILES/image*
rm OUTPUT_FILES/*.semd


#create adjoint sources
CODE_ADJ=../adj_mask.f90
gfortran $CODE_ADJ -o adj_run

cd SEM
for ((ii=1; ii<=$NREC; ii++))
do

    WF_DIR=`printf ../../WF_DIR/noise_cc_%02d/step_2/ $IREC`
    YTRACE=`printf "S%04d.AA.BXY" $ii`
    cp ../OUTPUT_ALL/step_2/$YTRACE.semd .
    TOFF=`../../get_time $NREC $ISRC $ii` 
    ../adj_run $YTRACE.semd $TOFF >> ../log.adj
    rename '.semd' '' $YTRACE.semd.adj

    XTRACE=`printf "S%04d.AA.BXX" $ii`
    awk '{printf(" %20.10f %20.10f\n",$1,0.)}' < $YTRACE.adj > $XTRACE.adj

    ZTRACE=`printf "S%04d.AA.BXZ" $ii`
    awk '{printf(" %20.10f %20.10f\n",$1,0.)}' < $YTRACE.adj > $ZTRACE.adj

done
cd ..


########### SIMULATION 3 ##########
echo "Simulation 3"
cp Par_file_noise_3  DATA/Par_file
./xmeshfem2D > log.mesh3
./xspecfem2D > log.spec3


#save results
mkdir OUTPUT_ALL/step_3
cp log.*                  OUTPUT_ALL/step_3
cp SEM/*Y.adj             OUTPUT_ALL/step_3
cp DATA/Par_file          OUTPUT_ALL/step_3
cp OUTPUT_FILES/proc*     OUTPUT_ALL/step_3
#cp OUTPUT_FILES/image*    OUTPUT_ALL/step_3
cp OUTPUT_FILES/snapshot* OUTPUT_ALL/
