#!/bin/bash

if [ $# -ne 2 ]; then echo "Usage:  change_rec  dir  nrec"; exit 1; fi
if [ ! -d $1 ];  then echo "Directory not found: $1"; exit 1; fi
if [ $2 -lt 1 ]; then echo "Need at least 1 receiver."; exit 1; fi

DIR=$1
NREC=$2

cd $DIR

for file in `ls Par_file*`
do

    echo $file

    Line1=`grep "^nrec\s" $file`

    if [ `echo $Line1 | wc -l` -ne 1 ]; then echo "Error reading file: $file."; exit 1; fi

    sed -i -e "s:${Line1}:nrec                            = ${NREC}:"  $file

done



