! XSUM_KERNELS_ASCII
!
! USAGE
!   NPROC bin/xsum_kernels_ascii INPUT_FILE OUTPUT_DIR
!
!
! COMMAND LINE ARGUMENTS
!   INPUT_FILE             - text file containing list of kernel directories
!   OUTPUT_PATH            - directory to which summed kernels are written
!
!
! DESCRIPTION
!   Sums kernels from directories specified in INPUT_FILE.
!   Writes the resulting sums to OUTPUT_DIR.
!
!   INPUT_FILE is a text file containing a list of absolute or relative paths to
!   kernel directories, one directory per line. Each kernel directory must
!   contain the following ASCII files, which are generated by SPECFEM2D when
!   adjoint simulation and ascii kernel options are specified:
!
!     proc000000_rhop_alpha_beta_kernel.dat
!     proc000000_rho_kappa_mu.dat
!
!   This routine is modeled after xsum_kernels in SPECFEM3D, in so far as
!   similarities between 2D and 3D packages allow.
!
!   TO DO: Move parameter definitions to postprocess_par module.


program sum_kernels_ascii

  implicit none

  integer, parameter :: MAX_KERNEL_PATHS = 65535
  integer, parameter :: MAX_STRING_LEN = 255

  integer, parameter :: NARGS = 2
  integer, parameter :: IIN = 20

  integer :: ipath, npath, iker, NLOCAL, i,j
  double precision, allocatable, dimension(:) :: kernel1, kernel2, kernel3
  double precision, allocatable, dimension(:) :: kernel_sum1, kernel_sum2, kernel_sum3
  double precision, allocatable, dimension(:,:) :: coord
  character(len=MAX_STRING_LEN) :: input_file, output_dir, kernel_name
  character(len=MAX_STRING_LEN) :: kernel_paths(MAX_KERNEL_PATHS)
  character(len=MAX_STRING_LEN) :: filename, arg(2), line
  integer :: ier
  double precision :: dummy1, dummy2


  write(*,*) 'Running XSUM_KERNELS_ASCII'
  write(*,*)

  if (command_argument_count() /= NARGS) then
    print *, 'USAGE: bin/xsum_kernels_ascii INPUT_FILE OUTPUT_DIR'
    print *, ''
    stop 'Please check command line arguments'
  endif

  ! parse command line arguments
  do i = 1, NARGS
    call get_command_argument(i,arg(i), status=ier)
  enddo

  read(arg(1),'(a)') input_file
  read(arg(2),'(a)') output_dir

  ! parse paths from INPUT_FILE
  npath=0
  open(unit = IIN, file = trim(input_file), status = 'old',iostat = ier)
  if (ier /= 0) then
     print *,'Error opening ',trim(input_file)
     stop 'Please check command line argument: INPUT_FILE'
  endif
  do while (1 == 1)
     read(IIN,'(a)',iostat=ier) line
     if (ier /= 0) exit
     npath = npath+1
     if (npath > MAX_KERNEL_PATHS) stop 'Error number of paths exceeds MAX_KERNEL_PATHS'
     kernel_paths(npath) = line
  enddo
  close(IIN)

  ! print status update
  write(*,*) 'Running XSUM_KERNELS_ASCII'
  write(*,*)

  write(*,*) 'Combining arrays from ',npath,' paths'
  write(*,*)

  ! allocate arrays
  call get_number_gll_points((kernel_paths(1)), NLOCAL)
  allocate( coord(2,NLOCAL) )
  allocate( kernel1(NLOCAL) )
  allocate( kernel2(NLOCAL) )
  allocate( kernel3(NLOCAL) )
  allocate( kernel_sum1(NLOCAL) )
  allocate( kernel_sum2(NLOCAL) )
  allocate( kernel_sum3(NLOCAL) )
  kernel1(:) = 0.0d0
  kernel2(:) = 0.0d0
  kernel3(:) = 0.0d0
  kernel_sum1(:) = 0.0d0
  kernel_sum2(:) = 0.0d0
  kernel_sum3(:) = 0.0d0

  ! sum kernels
  do iker = 1, 2

    if (iker == 1) write(kernel_name,'(a)') 'proc000000_rhop_alpha_beta_kernel.dat'
    if (iker == 2) write(kernel_name,'(a)') 'proc000000_rho_kappa_mu_kernel.dat'

    ! sum kernels
    do ipath = 1, npath
       filename = trim(kernel_paths(ipath)) //'/'// trim(kernel_name)
       open(unit=3,file=filename, status='old', action='read')
       do j = 1,nlocal
          read(3,*) dummy1, dummy2, kernel1(j), kernel2(j), kernel3(j)
       enddo
       close(3)

       if (ipath == 1) then
          kernel_sum1 = kernel1
          kernel_sum2 = kernel2
          kernel_sum3 = kernel3
       else
         kernel_sum1(:)=kernel_sum1(:)+kernel1(:)
         kernel_sum2(:)=kernel_sum2(:)+kernel2(:)
         kernel_sum3(:)=kernel_sum3(:)+kernel3(:)
       endif
    enddo

    ! save result
    filename = trim(output_dir) //'/'// trim(kernel_name)
    open(unit=4,file=filename,status='unknown',action='write')
    do j = 1, NLOCAL
          write(4,'(5e11.3)') coord(1,j),coord(2,j),kernel_sum1(j),kernel_sum2(j),kernel_sum3(j)
    enddo
    close(4)

  enddo

  write(*,*) 'Finished writing kernels '
  write(*,*)

end program sum_kernels_ascii


! ------------------------------------------------------------------------------

subroutine get_number_gll_points(kernel_path, NLOCAL)

  implicit none

  integer, parameter :: MAX_KERNEL_PATHS = 65535
  integer, parameter :: MAX_STRING_LEN = 255

  double precision :: dummy1, dummy2, dummy3, dummy4, dummy5

  character(len=MAX_STRING_LEN) :: kernel_path, filename

  integer :: j, ios, NLOCAL

  filename = trim(kernel_path)//'/'//'proc000000_rhop_alpha_beta_kernel.dat'
  open(unit=3,file=filename,status='old',action='read')
  NLOCAL = 0
  do j=1,MAX_KERNEL_PATHS
     read(3,*,iostat=ios) dummy1, dummy2, dummy3, dummy4, dummy5
     if (ios /= 0) exit
     NLOCAL=NLOCAL+1
  enddo
  close(3)

end subroutine get_number_gll_points

