#!/usr/bin/perl

#
#  Script to extract the function declarations in cuda files
#
#
# usage: ./create_specfem2D_gpu_cuda_method_stubs.pl
#             run in directory root SPECFEM2D/
#

$outfile = "src/cuda/specfem2D_gpu_cuda_method_stubs.c";


open(IOUT,"> _____temp_tutu_____");

$header = <<END;
/*
!========================================================================
!
!                   S P E C F E M 2 D  Version 7 . 0
!                   --------------------------------
!
!     Main historical authors: Dimitri Komatitsch and Jeroen Tromp
!                        Princeton University, USA
!                and CNRS / University of Marseille, France
!                 (there are currently many more authors!)
! (c) Princeton University and CNRS / University of Marseille, April 2014
!
! This software is a computer program whose purpose is to solve
! the two-dimensional viscoelastic anisotropic or poroelastic wave equation
! using a spectral-element method (SEM).
!
! This software is governed by the CeCILL license under French law and
! abiding by the rules of distribution of free software. You can use,
! modify and/or redistribute the software under the terms of the CeCILL
! license as circulated by CEA, CNRS and Inria at the following URL
! "http://www.cecill.info".
!
! As a counterpart to the access to the source code and rights to copy,
! modify and redistribute granted by the license, users are provided only
! with a limited warranty and the software's author, the holder of the
! economic rights, and the successive licensors have only limited
! liability.
!
! In this respect, the user's attention is drawn to the risks associated
! with loading, using, modifying and/or developing or reproducing the
! software by the user in light of its specific status of free software,
! that may mean that it is complicated to manipulate, and that also
! therefore means that it is reserved for developers and experienced
! professionals having in-depth computer knowledge. Users are therefore
! encouraged to load and test the software's suitability as regards their
! requirements in conditions enabling the security of their systems and/or
! data to be ensured and, more generally, to use and operate it in the
! same conditions as regards security.
!
! The full text of the license is available in file "LICENSE".
!
!========================================================================
*/

// this file has been automatically generated by script utils/create_specfem2D_gpu_cuda_method_stubs.pl

#include <stdio.h>
#include <stdlib.h>

#include "config.h"

typedef float realw;

END


$warning = <<END;
 fprintf(stderr,"ERROR: GPU_MODE enabled without GPU/CUDA Support. To enable GPU support, reconfigure with --with-cuda flag.\\n");
 exit(1);
END

print IOUT "$header\n";

$success = 0;

@objects = `ls src/cuda/*.cu`;

foreach $name (@objects) {
  chop $name;
  print "extracting word in file $name ...\n";

  print IOUT "\n//\n// $name\n//\n\n";

  # change tabs to white spaces
  system("expand -2 < $name > _____temp_tutu01_____");
  open(IIN,"<_____temp_tutu01_____");


  # open the source file
  $success = 1;
  $do_extract = 0;
  while($line = <IIN>) {
    chop $line;

    # suppress trailing white spaces and carriage return
    $line =~ s/\s*$//;

    # change the version number and copyright information
    #    $line =~ s#\(c\) California Institute of Technology and University of Pau, October 2007#\(c\) California Institute of Technology and University of Pau, November 2007#og;
    #    $line =~ s#rmass_sigma#rmass_time_integral_of_sigma#og;

    if($line =~ /extern "C"/){
      # new function declaration starts
      #print "$line\n";
      if( $line =~/FC_FUNC/ ){
        # function declaration on same line as extern, ask for line skip
        print "problem: please add a line break after extern 'C' here:";
        print "$line\n";
        $success = 0;
        close(IIN);
        exit;
      }
      $do_extract = 1;
      next;
    }

    # extract section
    if($do_extract == 1 ){
      # function declaration
      if($line =~ /{/){
        # function declaration ends
        if( $line =~ /INITIALIZE_CUDA_DEVICE/ ){
          # adds warning
          print IOUT "$line\n$warning\}\n\n";
        }else{
          print IOUT "$line\}\n\n";
        }
        $do_extract = 0;
      }else{
        # write line to the output file
        print IOUT "$line\n";
      }
      next;
    }
  }
  close(IIN);

  if( $success == 0 ){ exit; }
}

close(IOUT);
system("rm -f _____temp_tutu01_____");

# creates new stubs file if successful
if( $success == 1 ){
  print "\n\nsuccessfully extracted declarations \n\n";
  system("cp -p $outfile $outfile.bak");
  system("cp -p _____temp_tutu_____ $outfile");
  print "created new: $outfile \n";
}
system("rm -f _____temp_tutu_____");


