#!/bin/sh
NREC=$1
ISRC=$2
IREC=$3

XINC=`echo "scale=3; (2000-300)/($NREC-1)" | bc`
IOFF=`echo "scale=0; $IREC - $ISRC" | bc`
XOFF=`echo "scale=3; $IOFF*$XINC" | bc`
TOFF=`echo "scale=3; ($XOFF)/1300" | bc`
echo $TOFF
