#!/bin/bash

nrec=29

dir=`basename $PWD`

../clean;

for ((irec=1; irec<=$nrec; irec=irec+2))
do

    ii=`printf '%02d' $irec`
    echo -e "\nRECEIVER $ii of $nrec"

    ../run_fwd $nrec $irec
    ../run_adj $nrec $irec
    rm -rf ../${dir}_${ii}; mv OUTPUT_ALL ../${dir}_${ii}
    ../clean;

done

